# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
# SPDX-FileCopyrightText: Open Energy Transition gGmbH
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: lowflex_2030_vres

scenario:
  clusters:
  - 33
  sector_opts:
  - 3H
  planning_horizons:
  - 2030

snapshots:
  start: '2022-01-01'
  end: '2023-01-01'

electricity:
  custom_powerplants: true
  custom_powerplants_fn: "data/custom_ppl_2030_lowflex.csv"
  powerplants_filter: Fueltype in ['Remove everything']

  estimate_renewable_capacities:
    enable: false
    from_gem: false

atlite:
  default_cutout: europe-2022-sarah3-era5

pypsa_eur:
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - offwind-float
  - solar-hsat
  - solar
  - ror
  - solar-rooftop
  StorageUnit:
  - PHS
  - hydro
  - battery
  - home_battery_storage

sector:
  bev_dsm: true
  v2g: 0
  bev_dsm_availability: 0.15
  land_transport_electric_share:
    2030: "data/ember_data/land_transport_electric_share_2030.csv"
  land_transport_ice_share:
    2030: "data/ember_data/land_transport_ice_share_2030.csv"
  bev_energy: 0.08
  bev_charge_efficiency: 0.9
  bev_battery_central_soc: 0.5
  bev_charge_rate: 0.01012
  bev_avail_max: 0.2
  bev_avail_min: 0.02
  transport_electric_efficiency: 53.19
  residential_heat:
    dsm:
      enable: true
      direction:
      - overheat
      restriction_value:
        2030: 0.03
      restriction_time:
      - 8
      - 17
  chp:
    enable: false
  hydrogen_underground_storage: false

costs:
  year: 2030
  fuel:
    gas: 27.1
    coal: 12.1
    lignite: 8.6
    oil: 42.2
    uranium: 1.8
  VOM:
    OCGT: 1
    CCGT: 1
    coal: 2.3
    lignite: 2.3
  emission_prices:
    enable: true
    co2: 79.9
  custom_cost_fn: data/custom_costs_ember.csv

solving:
  agg_p_nom_limits:
    agg_heat_pumps: true
    include_existing: false
    file: data/agg_p_nom_minmax.csv
  constraints:
    CCL: true

ember_settings:
  ntc_data: "data/ember_data/ntc_2030.csv"
  ntc_cross_country_pf_restriction: false
  ramping: false
  nuclear_decommissioning: false
  ember_gas_price: true
  hourly_carbon_prices: false
  chp_countries:
    Poland: PL
    Czechia: CZ
    Greece: GR
    Germany: DE
    Italy: IT
    Netherlands: NL
  filter_chps: "DateIn <= 2030 and DateOut >= 2030 and type == 'chp' and status == 'operating' and bus in @focus_full"
  chp_data: "data/ember_data/combined_chp_2030.csv"
  add_LV_capacities: true
  remove_heat_storage: true
  apply_highflex_capacities:
    resistive_heaters: true
    water_tanks: true
    heat_pumps: true
