run:
  name: scenario_2030_flex_on
scenario:
  clusters:
  - 39
  sector_opts:
  - 17H
  planning_horizons:
  - 2030
snapshots:
  start: '2023-01-01'
  end: '2024-01-01'
countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK'] #, 'XK']
atlite:
  default_cutout: europe-2023-sarah3-era5
  nprocesses: 4
  show_progress: true
  cutouts:
    # use 'base' to determine geographical bounds and time span from config
    # base:
      # module: era5
    europe-2023-sarah3-era5:
      time: ['2023', '2023']
renewable:
  onwind:
    correction_factor: 0.93
  solar:
    correction_factor: 0.854337
lines:
  s_max_pu: 1
links:
  under_construction: remove
  max_extension: 0
transmission_projects:
  enable: false
pypsa_eur:
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - offwind-float
  - solar-hsat
  - solar
  - ror
  - solar-rooftop
  StorageUnit:
  - PHS
  - hydro
  - battery
  - home_battery_storage
  
electricity:
  conventional_generation:
    from_entsoe: false
    year: 2030
  extendable_carriers:
    Generator: []
    StorageUnit: []
    Store: []
  transmission_limit: v1.0
  custom_powerplants_fn: "data/custom_ppl_2030.csv"
  custom_powerplants: (DateIn <= 2030 and DateOut >= 2030)
  powerplants_filter: (Fueltype not in ['Nuclear', 'Hard Coal', 'Lignite', 'Natural Gas'] and DateIn <= 2030 and DateOut >= 2030)
  estimate_renewable_capacities:
    enable: false
    from_gem: false
    technology_mapping:
  
load:
  manual_adjustments: false
  scaling_factor: 1.0
sector:
  transport: true
  heating: true
  biomass: true
  industry: true
  shipping: false
  aviation: false
  agriculture: false
  gas_network: false
  bev_dsm: true
  v2g: true 
  land_transport_electric_share: 0.3
  bev_dsm_availability: 1
  bev_energy: 0.05
  bev_charge_efficiency: 0.9
  bev_charge_rate: 0.35
  bev_avail_max: 0.95
  bev_avail_mean: 0.8
  bev_dsm_restriction_value: 0.4
  bev_dsm_restriction_time: 7
  transport_electric_efficiency: 53.19
  transport_heating_deadband_upper: 20
  transport_heating_deadband_lower: 15
  EV_lower_degree_factor: 0.98
  EV_upper_degree_factor: 0.8
  time_dep_hp_cop: true
  tes: true
  tes_tau:
    decentral: 3
    central: 180
  marginal_cost_heat_vent: 0.02
  heat_pump_sink_T: 55
  heat_source_cooling: 6
  heat_pump_cop_approximation:
  refrigerant: ammonia
  home_battery_storage: true
  
  conventional_generation:
    OCGT: gas
    CCGT: gas
    coal: coal
    lignite: lignite
    nuclear: uranium
    oil: oil
  keep_existing_capacities: true
costs:
  year: 2030
  fuel:
    gas: 19.9
    coal: 10.7
    lignite: 8.5
    oil: 28.2
  VOM:
    OCGT: 1
    CCGT: 1
    coal: 2.3
    lignite: 2.3
  emission_prices:
    enable: true
    co2: 69.6
  
clustering:
  exclude_carriers:
  - coal
  - nuclear
  - lignite
simplify_network:
  remove_stubs_across_borders: true
ember_settings:
  ntc_data: "data/ember_data/ntc.csv"
  ntc_cross_country_pf_restriction: false
  ramping: false
  nuclear_decommissioning: false
  ember_gas_price: true
  hourly_carbon_prices: false
  historical_ntc: true
  chp_countries:
    Poland: PL
    Czechia: CZ
    Greece: GR
    Germany: DE
    Italy: IT
    Netherlands: NL
  filter_chps: "DateIn <= 2030 and DateOut >= 2030"
  chp_data: "data/ember_data/combined_chp_2030.csv"
  
